[project]
name = "mcpxcode"
version = "0.1.0"
description = "MCPXcode is an open-source implementation of the Model Context Protocol (MCP) for Xcode."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.5.0",
]
